PL/Models/Peliculas.cs
namespace PL.Models
{
    public class Peliculas
    {
        public int id { get; set; }
        public string overview { get; set; }
        public string title { get; set; }
        public string poster_path { get; set; }
        public string release_date { get; set; }

        public List<object> PeliculasL { get; set; }

    }
}

PL/Controllers/PeliculasController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using PL.Models;
using System.Net.Http.Json;

namespace PL.Controllers
{
    public class PeliculasController : Controller
    {
        public IActionResult GetAllPeliPopu(int? page)
        {
         Movie movie = new Movie();
             using (var client  = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");
                page = page == null ? 1 : page;
                string url = "movie/popular?api_key=f13a3c8901fa3f119654955fdba88ead&language=es-Es&page=" + page;
              
                var responseTask = client.GetAsync(url);
                responseTask.Wait();

                var resultadoServicio = responseTask.Result;
                if (resultadoServicio.IsSuccessStatusCode)
                {
                    var readTask = resultadoServicio.Content.ReadAsStringAsync();
                    dynamic resultJson = JObject.Parse(readTask.Result);
                    readTask.Wait();
                    movie.Movies = new List<object>();
                     foreach(var item in resultJson.results) 
                    {
                        Movie movies = new Movie();
                        movies.IdMovie = item.id;
                        movies.Description = item.overview;
                        movies.Title = item.title;
                        movies.Image = "https://image.tmdb.org/t/p/w600_and_h900_bestv2" + item.poster_path;
                        movies.date = item.release_date;
                        movie.Movies.Add(movies);
                    }
                    //var readTask = resultadoServicio.Content.ReadFromJsonAsync<Models.Result>();
                    //readTask.Wait();

                    //foreach(var item in readTask.Result.Objects) 
                    //{ 
                    //    PL.Models.Peliculas ResultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<PL.Models.Peliculas>(readTask.Result.Object.ToString());
                    //    root.results.Add(ResultItemList);
                    //}
                }
            }
             ViewBag.page = page;
            return View(movie);
        }
        
        public ActionResult AddPeliculas(int idMovie)
        {
            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");
                var json = new
                {
                    media_type = "movie",
                    media_id = (int)idMovie,
                    favorite = true,
                };
                var postTask = client.PostAsJsonAsync("account/20522392/favorite?api_key=f13a3c8901fa3f119654955fdba88ead&session_id=29d267ed58400990f5b5503392b7ef45a373f48", json);
                postTask.Wait();

                var result = postTask.Result;
                if(result.IsSuccessStatusCode)
                {
                    ViewBag.Mensaje = "Pelicula agregada a tus favoritos";
                }
                else
                {
                    ViewBag.Mensaje = "Error al intentara añadir la pelicula a tus favoritos";
                }
                
            }
            return PartialView("Modal");
        }
        public IActionResult GetAllPeliFav(int? page)
        {
            Movie movie = new Movie();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");

                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");
                page = page == null ? 1 : page;
                string url = "account/20522392/favorite?api_key=f13a3c8901fa3f119654955fdba88ead&session_id=29d267ed58400990f5b5503392b7ef45a373f48page=" + page;
                //if (page == null)
                //{
                //    url = "movie/popular?api_key=f13a3c8901fa3f119654955fdba88ead&language=es-Es";
                //}
                ////else
                ////{
                ////    url = "movie/popular?api_key=f13a3c8901fa3f119654955fdba88ead&language=es-Es&page";
                ////}
                var responseTask = client.GetAsync(url);
                responseTask.Wait();

                var resultadoServicio = responseTask.Result;
                if (resultadoServicio.IsSuccessStatusCode)
                {
                    var readTask = resultadoServicio.Content.ReadAsStringAsync();
                    dynamic resultJson = JObject.Parse(readTask.Result);
                    readTask.Wait();
                    movie.Movies = new List<object>();
                    foreach (var item in resultJson.results)
                    {
                        Movie movies = new Movie();
                        movies.IdMovie = item.id;
                        movies.Description = item.overview;
                        movies.Title = item.title;
                        movies.Image = "https://image.tmdb.org/t/p/w600_and_h900_bestv2" + item.poster_path;
                        movies.date = item.release_date;
                        movie.Movies.Add(movies);
                    }
                    //var readTask = resultadoServicio.Content.ReadFromJsonAsync<Models.Result>();
                    //readTask.Wait();

                    //foreach(var item in readTask.Result.Objects) 
                    //{ 
                    //    PL.Models.Peliculas ResultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<PL.Models.Peliculas>(readTask.Result.Object.ToString());
                    //    root.results.Add(ResultItemList);
                    //}
                }
            }
            ViewBag.page = page;
            return View(movie);
        }
        [HttpPost]
        public ActionResult DeletePeliculas(int idMovie)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");
                var json = new
                {
                    media_type = "movie",
                    media_id = (int)idMovie,
                    favorite = false,
                };
                var postTask = client.PutAsJsonAsync($"account/20522392/favorite?api_key=f13a3c8901fa3f119654955fdba88ead?session_id=29d267ed58400990f5b5503392b7ef45a373f48", json);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.Mensaje = "Pelicula eliminada de favoritos";
                }
                else
                {
                    ViewBag.Mensaje = "Error al intentara eliminar la pelicula de tus favoritos";
                }

            }
            return PartialView("Modal");
        }

    }
}

PL/Views/Peliculas/GetAllPeliFav.cshtml
@model Movie;
@{
    ViewData["Title"] = "GetAllPeliFav";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="height: 300%">
    <div class="text-lg-start">
        <h2>Peliculas Populares</h2>
    </div>
    <hr />
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = ViewBag.page-1}) tabindex = " -1">Previous</a></li>
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = 1})">1</a></li>
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = 2})"></a></li>
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = 3})">3</a></li>
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = ViewBag.page+1})">Next</a></li>
        </ul>
    </nav>
    <div class="row justify-content-center">
        @foreach (Movie movie in Model.Movies)
        {

            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="@movie.Image" alt="Card image cap" width="150" height="225">
                        <div class="card-body limited-text">
                            <h5 class="card-title fs-1">@movie.Title</h5>
                            <p class="card-text ">@movie.Description</p>
                            <h6>@movie.date</h6>
                            <p class="card-text">
                                <a href="@Url.Action("DelePeliculas","Peliculas", new {idMovie = movie.IdMovie})" class="btn btn-outline-danger"><i class="bi bi-heart"></i></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

PL/Views/Peliculas/GetAllPeliPopu.cshtml
@model Movie;
@{
    ViewData["Title"] = "GetAllPeliPopu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="height: 300%">
    <div class="text-lg-start">
        <h2>Peliculas Populares</h2>
    </div>
    <hr />
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = ViewBag.page-1}) tabindex = "-1">Previous</a></li>
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = 1})">1</a></li>
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = 2})"></a></li>
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = 3})">3</a></li>
            <li class="page-item"><a class="page-link" href="@Url.Action("GetAllPeliPopu", "Peliculas", new {page = ViewBag.page+1})">Next</a></li>
        </ul>
    </nav>
            <div class="row justify-content-center">
                @foreach (Movie movie in Model.Movies)
                {

                    <div class="col-4">
                        <div class="card" style="width: 18rem;">
                            <div class="card" style="width: 18rem;">
                                <img class="card-img-top" src="@movie.Image" alt="Card image cap" width="150" height="225">
                                    <div class="card-body limited-text">
                                    <h5 class="card-title fs-1">@movie.Title</h5>
                                    <p class="card-text ">@movie.Description</p>
                                    <h6>@movie.date</h6>
                                    <p class="card-text">
                                <a href="@Url.Action("AddPeliculas","Peliculas", new {idMovie = movie.IdMovie})" class="btn btn-outline-danger"><i class="bi bi-heart"></i></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
            }
        </div>
</div>

PL/Views/Peliculas/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Vale", "GetAllPeliPopu", "Peliculas", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Peliculas/view.cshtml
<!DOCTYPE html>

<html>
<head>
    <link href="~/css/EstiloCard.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <div class="row">
            <div class="example-1 card">
                <div class="wrapper">
                    <div class="date">
                        <span class="day">12</span>
                        <span class="month">Aug</span>
                        <span class="year">2016</span>
                    </div>
                    <div class="data">
                        <div class="content">
                            <span class="author">Jane Doe</span>
                            <h1 class="title"><a href="#">Boxing icon has the will for a couple more fights</a></h1>
                            <p class="text">The highly anticipated world championship fight will take place at 10am and is the second major boxing blockbuster in the nation after 43 years.</p>
                            <label for="show-menu" class="menu-button"><span></span></label>
                        </div>
                        <input type="checkbox" id="show-menu" />
                        <ul class="menu-content">
                            <li>
                                <a href="#" class="fa fa-bookmark-o"></a>
                            </li>
                            <li><a href="#" class="fa fa-heart-o"><span>47</span></a></li>
                            <li><a href="#" class="fa fa-comment-o"><span>8</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="example-2 card">
                <div class="wrapper">
                    <div class="header">
                        <div class="date">
                            <span class="day">12</span>
                            <span class="month">Aug</span>
                            <span class="year">2016</span>
                        </div>
                        <ul class="menu-content">
                            <li>
                                <a href="#" class="fa fa-bookmark-o"></a>
                            </li>
                            <li><a href="#" class="fa fa-heart-o"><span>18</span></a></li>
                            <li><a href="#" class="fa fa-comment-o"><span>3</span></a></li>
                        </ul>
                    </div>
                    <div class="data">
                        <div class="content">
                            <span class="author">Jane Doe</span>
                            <h1 class="title"><a href="#">Stranger Things: The sound of the Upside Down</a></h1>
                            <p class="text">The antsy bingers of Netflix will eagerly anticipate the digital release of the Survive soundtrack, out today.</p>
                            <a href="#" class="button">Read more</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @RenderBody()
    </div>
</body>
</html>