PL/Controllers/DulceriaController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using iText.IO.Image;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using iText.Kernel.Colors;

namespace PL.Controllers
{
    public class DulceriaController : Controller
    {
        public IActionResult GetAll()
        {

            return View();
        }
        [HttpGet]
        public IActionResult ProductosGetAll()
        {
            ML.Producto producto = new ML.Producto();
            ML.Result result = BL.Producto.GetAll();

            if (result.Correct)
            {
                producto.Productos = result.Objects;
            }
            else
            {
                return View();
            }
            return View(producto);
        }
        public IActionResult AddCarrito(int idProducto)
        {
            bool existe = false;
            ML.Venta carrito= new ML.Venta();
            carrito.Carrito = new List<object>();
            ML.Result result = BL.Producto.GetById(idProducto);

            if (HttpContext.Session.GetString("Carrito") == null)
            {
                if (result.Correct)
                {
                    ML.Producto producto = (ML.Producto)result.Object;
                    producto.Cantidad = 1;
                    carrito.Carrito.Add(producto);
                    //serializar correcto
                    HttpContext.Session.SetString("Carrito", Newtonsoft.Json.JsonConvert.SerializeObject(carrito.Carrito));

                }
            }
            else
            {
                ML.Producto producto=(ML.Producto)result.Object;
                GetCarrito(carrito); //se recupera el carrito
                foreach (ML.Producto productoM in carrito.Carrito)
                {
                    if (producto.IdProducto == productoM.IdProducto)
                    {
                        productoM.Cantidad += 1;
                        existe = true;
                        break;
                    }
                    else
                    {
                        existe = false;
                    }
                }
                    if (existe == true)
                    {
                        HttpContext.Session.SetString("Carrito", Newtonsoft.Json.JsonConvert.SerializeObject(carrito.Carrito));
                    }
                    else
                    {
                        producto.Cantidad = 1;
                        carrito.Carrito.Add(producto);
                        HttpContext.Session.SetString("Carrito", Newtonsoft.Json.JsonConvert.SerializeObject(carrito.Carrito));
                    }
                }

            return RedirectToAction("ProductosGetAll");
        }
        public ML.Venta GetCarrito(ML.Venta carrito)
        {
            var ventaSession = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(HttpContext.Session.GetString("Carrito"));
            foreach(var obj in ventaSession)
            {
                ML.Producto objMateria = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(obj.ToString());
                carrito.Carrito.Add(objMateria);
            }
            return carrito;
        }
        public ActionResult carrito()
        {
            ML.Venta carrito = new ML.Venta();
            carrito.Carrito = new List<object>();
            if(HttpContext.Session.GetString("Carrito") == null)
            {
                return View(carrito);
            }
            else
            {
                GetCarrito(carrito);
                return View(carrito);
            }
        }
        public ActionResult DeleteCarro()
        {
            if (HttpContext.Session.GetString("Carrito") != null)
            {
                HttpContext.Session.Remove("Carrito");
            }
            return RedirectToAction("ProductosGetAll");
        }
        public ActionResult AgregarElemento(int idProducto)
        {
            bool existe = false;
            ML.Venta carrito = new ML.Venta();
            carrito.Carrito = new List<object>();
            ML.Result result = BL.Producto.GetById(idProducto);

            if (HttpContext.Session.GetString("Carrito") == null)
            {
                if (result.Correct)
                {
                    ML.Producto producto = (ML.Producto)result.Object;
                    producto.Cantidad = 1;
                    carrito.Carrito.Add(producto);
                    //serializar correcto
                    HttpContext.Session.SetString("Carrito", Newtonsoft.Json.JsonConvert.SerializeObject(carrito.Carrito));

                }
            }
            else
            {
                ML.Producto producto = (ML.Producto)result.Object;
                GetCarrito(carrito); //se recupera el carrito
                foreach (ML.Producto productoM in carrito.Carrito)
                {
                    if (producto.IdProducto == productoM.IdProducto)
                    {
                        productoM.Cantidad += 1;
                        existe = true;
                        break;
                    }
                    else
                    {
                        existe = false;
                    }
                }
                if (existe == true)
                {
                    HttpContext.Session.SetString("Carrito", Newtonsoft.Json.JsonConvert.SerializeObject(carrito.Carrito));
                }
                else
                {
                    producto.Cantidad = 1;
                    carrito.Carrito.Add(producto);
                    HttpContext.Session.SetString("Carrito", Newtonsoft.Json.JsonConvert.SerializeObject(carrito.Carrito));
                }
            }

            return RedirectToAction("carrito");
        }
        
        public ActionResult EliminarProductos(int idProducto)
        {
            return View();
        }

        public ActionResult GenerarPDF()
        {
            ML.Venta venta = new ML.Venta();
            venta.Carrito = new List<object>();
            GetCarrito(venta);

            // Crear un nuevo documento PDF en una ubicación temporal
            string rutaTempPDF = Path.GetTempFileName() + ".pdf";

            using (PdfDocument pdfDocument = new PdfDocument(new PdfWriter(rutaTempPDF)))
            {
                using (Document document = new Document(pdfDocument))
                {
                    document.Add(new Paragraph("Resumen de la Compra"));

                    // Crear la tabla para mostrar la lista de objetos
                    iText.Layout.Element.Table table = new iText.Layout.Element.Table(5); // 5 columnas
                    table.SetWidth(UnitValue.CreatePercentValue(100)); // Ancho de la tabla al 100% del documento

                    // Añadir las celdas de encabezado a la tabla
                    
                    
                    table.AddHeaderCell("ID Producto").SetFontColor(ColorConstants.WHITE);
                    table.AddHeaderCell("Producto").SetBackgroundColor(ColorConstants.BLACK);
                    table.AddHeaderCell("Precio Unitario");
                    table.AddHeaderCell("Cantidad");
                    table.AddHeaderCell("Imagen");
                    

                    


                    foreach (ML.Producto producto in venta.Carrito)
                    {
                        table.AddCell(producto.IdProducto.ToString());
                        table.AddCell(producto.Nombre);
                        table.AddCell(producto.Precio.ToString());
                        table.AddCell(producto.Cantidad.ToString());
                        byte[] imageBytes = Convert.FromBase64String(producto.Imagen);
                        ImageData data = ImageDataFactory.Create(imageBytes);
                        Image image = new Image(data);
                        table.AddCell(image.SetWidth(50).SetHeight(50));

                    }

                    // Añadir la tabla al documento
                    document.Add(table);
                }
            }

            // Leer el archivo PDF como un arreglo de bytes
            byte[] fileBytes = System.IO.File.ReadAllBytes(rutaTempPDF);

            // Eliminar el archivo temporal
            System.IO.File.Delete(rutaTempPDF);
            HttpContext.Session.Remove("Carrito");

            // Descargar el archivo PDF
            return new FileStreamResult(new MemoryStream(fileBytes), "application/pdf")
            {
                FileDownloadName = "ReporteProductos.pdf"
            };
        }
    }
}

PL/Views/Dulceria/ProductosGetAll.cshtml
@model ML.Producto
@{
    ViewData["Title"] = "ProductosGetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    .product-grid{ font-family: 'Titillium Web', sans-serif; }
.product-grid .product-image{
    position: relative;
    overflow: hidden;
}
.product-grid .product-image a.image{ display: block; }
.product-grid .product-image img{
    width: 100%;
    height: auto;
    transition: all 0.3s ease 0s;
}
.product-grid .product-image:hover img{ opacity: 0.8; }
.product-grid .product-links{
    padding: 0;
    margin: 0;
    list-style: none;
    position: absolute;
    top: 10px;
    left: 13px;
}
.product-grid .product-links li{
    margin: 0 0 8px;
    opacity: 0;
    transform: translateX(20px);
    transition: all 0.3s ease 0s;
}
.product-grid .product-links li:nth-child(even){ transform: translateX(-20px); }
.product-grid:hover .product-links li{
    opacity: 1;
    transform: translateX(0);
}
.product-grid .product-links li a{
    color: #0775c0;
    background: #fff;
    font-size: 15px;
    text-align: center;
    line-height: 35px;
    width: 35px;
    height: 35px;
    box-shadow: 0 0 5px rgba(0,0,0,0.3);
    display: block;
    position: relative;
    transition: all 0.3s ease 0s;
}
.product-grid .product-links li a:hover{
    color: #fff;
    background: #0775c0;
}
.product-grid .product-links li a:before{
    content: '';
    height: 100%;
    width: 100%;
    border: 1px solid #0775c0;
    border-top: none;
    border-right: none;
    position: absolute;
    left: -4px;
    top: 4px;
    z-index: -1;
    transition: all 0.3s ease;
}
.product-grid .product-links li a:hover:before{
    left: 0;
    top: 0;
}
.product-grid .product-content{
    background: linear-gradient(transparent,#f5f5f5);
    padding: 10px;
}
.product-grid .title{
    font-size: 15px;
    font-weight: 700;
    letter-spacing: 0.5px;
    text-transform: uppercase;
    margin: 0 0 3px;
}
.product-grid .title a{
    color: #333;
    transition: all 0.3s ease;
}
.product-grid .title a:hover{ color: #0775c0; }
.product-grid .price{
    color: #555;
    font-size: 15px;
    font-weight: 500;
}

</style>

<div class="text-lg-start">
    <h2>Dulceria</h2>
    <h5>Selecciona tus dulces favoritos</h5>
</div>
<hr />

<div class="row">
    @foreach(ML.Producto producto in Model.Productos)
    {
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="" class="image">
                        <img class="pic-1" src="data:imagen/*;base64,@producto.Imagen">
                </a>
                <ul class="product-links">
                    <li><a href="#" data-tip="Add to Wishlist"><i class="fas fa-heart"></i></a></li>
                    <li><a href="#" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="@Url.Action("AddCarrito","Dulceria", new {idProducto = producto.IdProducto})" data-tip="Add to Cart"><i class="fa fa-shopping-bag"></i></a></li>
                </ul>
            </div>
            <div class="product-content">
                <h3 class="title"><a href="#">@producto.Nombre</a></h3>
                <div class="price">$@producto.Precio</div>
            </div>
        </div>
    </div>
    }
    
</div>

PL/Views/Dulceria/carrito.cshtml
@model ML.Venta
@{
    ViewData["Title"] = "carrito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="text-center">
        <h1>Tu Carrito</h1>
    </div>
    <hr />

    @if (Model.Carrito == null || Model.Carrito.Count == 0)
    {
        <div class="alert alert-warning" role="alert">
            Aun no tienes productos agregados ):
        </div>
    }
    else
    {
        <div class="btn-group d-flex" role="group" aria-label="Button group with nested dropdown">
            <button type="button" onclick="AbrirModal()" class="btn btn-dark"><i class="fa-solid fa-money-bill"></i> Comprar</button>
            <a type="button" class="btn btn-dark" href="@Url.Action("DeleteCarro", "Dulceria")"><i class="fa-solid fa-broom"></i> Limpiar</a>
            <a type="button" class="btn btn-outline-danger" href="@Url.Action("ProductosGetAll", "Dulceria")"><i class="fa-solid fa-door-open"></i> Regresar</a>
        </div>
        <br />
        <table class="table table-dark table-hover table-bordered table-responsive">
            <thead>
                <tr class="table-secondary">
                    <td class="text-center">Nombre</td>
                    <td class="text-center">Precio</td>
                    <td class="text-center">Imagen</td>
                    <td class="text-center">Agregar</td>
                    <td class="text-center">cantidad</td>
                    <td class="text-center">Quitar</td>
                    <td class="text-center">Eliminar</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Producto producto in Model.Carrito)
                {
                    <tr>
                        <td>@producto.Nombre</td>
                        <td>$ @producto.Precio</td>
                        @if (producto.Imagen != null)
                        {
                            <td class="text-center"><img id="Img" src="data:image/*;base64,@producto.Imagen" style="width:50px ; height:50px" /></td>
                        }
                        else
                        {
                            <td class="text-center"><img id="Img" src="https://st.depositphotos.com/2934765/53192/v/450/depositphotos_531920820-stock-illustration-photo-available-vector-icon-default.jpg" style="width:50px ; height:50px" /></td>
                        }

                        <td><a class="btn btn-success" href="@Url.Action("AgregarElemento","Dulceria", new {idProducto = producto.IdProducto})"><i class="fa-solid fa-square-plus"></i></a> </td>
                        <td>@producto.Cantidad </td>
                        <td><button class="btn btn-warning"><i class="fa-solid fa-square-minus"></i></button> </td>
                        <td><button class="btn btn-danger"><i class="fa-solid fa-trash-can"></i></button> </td>
                    </tr>

                }
            </tbody>
        </table>
        <label>Total: $ @Model.Total</label>
        <input type="text" id="txtLatitud" hidden />
        <input type="text" id="txtLongitud" hidden />
    }
</div>
<div class="modal fade " id="Modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        @using (Html.BeginForm("Index", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="modal-content">
                <div class="modal-header alert-secondary">
                    <h5 class="modal-title" id="exampleModalLabel">Termina tu compra</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <table class="table table-dark table-hover table-bordered table-responsive">
                    <thead>
                        <tr class="table-secondary">
                            <td class="text-center">Nombre</td>
                            <td class="text-center">Precio</td>
                            <td class="text-center">Imagen</td>
                            <td class="text-center">cantidad</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.Producto producto in Model.Carrito)
                        {
                            <tr>
                                <td>@producto.Nombre</td>
                                <td>$ @producto.Precio</td>
                                @if (producto.Imagen != null)
                                {
                                    <td class="text-center"><img id="Img" src="data:image/*;base64,@producto.Imagen" style="width:50px ; height:50px" /></td>
                                }
                                else
                                {
                                    <td class="text-center"><img id="Img" src="https://st.depositphotos.com/2934765/53192/v/450/depositphotos_531920820-stock-illustration-photo-available-vector-icon-default.jpg" style="width:50px ; height:50px" /></td>
                                }
                                <td>@producto.Cantidad </td>
                            </tr>
                        }
                    </tbody>
                </table>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
                    <a onclick="ModalCompra()" id="btnGuardar" class="btn btn-dark"><i class="fa-solid fa-truck"></i>Comprar</a>
                </div>
            </div>
        }
    </div>
</div>
<div class="modal fade " id="ModalCompra" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header alert-success">
                <h5 class="modal-title" id="exampleModalLabel">Completado! <i class="fa-solid fa-check"></i></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row text-center">
                    <h2 class="text-center">Tu pedido esta en proceso!</h2>
                    <img src="https://i.pinimg.com/originals/62/dd/c4/62ddc455488a13d67f4198a09dc4bb29.gif" width="50" height="400" />
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Salir</button>
                <a href="@Url.Action("GenerarPDF")" id="btnGuardar" class="btn btn-dark"><i class="fa-solid fa-file-pdf"></i> Resumen</a>
            </div>
        </div>
    </div>

</div>
@section Scripts{
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript">
        function AbrirModal() {
            $('#Modal').modal('show');
        }
        function ModalCompra() {
            $('#Modal').modal('hide');
            $('#ModalCompra').modal('show');
        }
        
        </script>
}