PL/Controllers/CineController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using PL.Models;
using System.Drawing.Drawing2D;
using System.Security.Policy;

namespace PL.Controllers
{
    public class CineController : Controller
    {
        public IActionResult GetAll()
        {
            ML.Cine cine = new ML.Cine();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5087/api/Cine/");
                var responseTask = client.GetAsync("GetAll/");
                responseTask.Wait();
                var resultadoServicio = responseTask.Result;
                if (resultadoServicio.IsSuccessStatusCode)
                {
                    var readTask = resultadoServicio.Content.ReadAsStringAsync();
                    dynamic resultJ = JObject.Parse(readTask.Result);
                    readTask.Wait();
                    cine.Cines = new List<object>();

                    foreach (var item in resultJ.objects)
                    {
                        ML.Cine cines = new ML.Cine();
                        cines.IdCine = item.idCine;
                        cines.Nombre = item.nombre;
                        cines.Direccion = item.direccion;
                        cines.Zona = new ML.Zona();
                        cines.Zona.IdZona = item.zona.idZona;
                        cines.Zona.Nombre = item.zona.nombre;
                        cines.Ventas = item.ventas;
                        cine.Cines.Add(cines);
                    }
                }
            }
          return View(cine);
        }
        [HttpGet]
        public IActionResult Form(int? IdCine)
        {

            ML.Cine cine = new ML.Cine();
           
            
            if (IdCine != null)
            {
                cine.IdCine = (int)IdCine;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:5087/api/Cine/");
                    var responseTask = client.GetAsync($"GetById/{IdCine}");
                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadFromJsonAsync<ML.Result>();
                        readTask.Wait();

                        ML.Cine resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Cine>(readTask.Result.Object.ToString());
                        cine = resultItemList;
                    }
                    return View(cine);
                }
            }
            else
            {

            }
            return View(cine);
        }
        [HttpPost]
        public IActionResult Form(ML.Cine cine)
        {
            if (cine.IdCine == 0)
            {
                ML.Result result = new ML.Result();
                using (var client = new HttpClient())
                {
                    //client.BaseAddress = new Uri("http://localhost:5087/api/Cine/");
                    var postTask = client.PostAsJsonAsync("http://localhost:5087/api/Cine/Add", cine);
                    postTask.Wait();

                    var resultServicio = postTask.Result;
                    if (resultServicio.IsSuccessStatusCode)
                    {
                        ViewBag.Mensaje = "Se ha registrado correctamente El cine";
                    }
                    else
                    {
                        ViewBag.Mensaje = "Error al registrar el cine";
                    }

                }
            }
            else
            {

                ML.Result result = new ML.Result();
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:8115/api/");
                    var postTask = client.PutAsJsonAsync<ML.Cine>("Update", cine);
                    postTask.Wait();

                    var resultServicio = postTask.Result;
                    if (resultServicio.IsSuccessStatusCode)
                    {
                        ViewBag.Mensaje = "Se ha registrado correctamente la materia";
                    }
                    else
                    {
                        ViewBag.Mensaje = "Error al registrar la materia";
                    }
                }
            }
            return PartialView("Modal");

        }
        [HttpGet]
        public IActionResult Delete(ML.Cine cine)
        {
            ML.Result result = new ML.Result();
             int id = cine.IdCine;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5087/api/Cine/");
                var postTask = client.DeleteAsync("Delete/" + id);
                postTask.Wait();

                var resultServicio = postTask.Result;
                if (resultServicio.IsSuccessStatusCode)
                {
                    ViewBag.Mensaje = "Se ha eliminado correctamente el cine";
                }
                else
                {
                    ViewBag.Mensaje = "Error al Eliminar el cine";
                }
            }
            return PartialView("Modal");
        }
    }
}

PL/Views/Cine/Form.cshtml
@model ML.Cine
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-lg-start">
    <h2>Cines</h2>
    <h5>Ingrese los datos del Cine</h5>
</div>
<hr />
<style type="text/css">
    #map {
        height: 400px;
        width: 100%;
    }
</style>
@using (Html.BeginForm("Form", "Cine", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(Model => Model.IdCine, new {@Id="txtIdCine"})
    <div class="container text-center">
        <div class="row align-items-start">

            <div class="col">

                @Html.LabelFor(model => Model.Nombre, new { @class = "hidden" })
                @Html.TextBoxFor(model => Model.Nombre, new { @class = "form-control hidden", @onkeypress = "return lettersOnly(event, 'lblErrorNombre')" })
            </div>
            <div class="col">
                @Html.LabelFor(model => Model.Zona.IdZona, new { @class = "hidden" })
                @Html.TextBoxFor(model => Model.Zona.IdZona, new { @class = "form-control hidden", @onkeypress = "return lettersOnly(event, 'lblErrorNombre')" })
            </div>
            <div class="col">
                @Html.LabelFor(model => Model.Ventas, new { @class = "hidden" })
                @Html.TextBoxFor(model => Model.Ventas, new { @class = "form-control hidden" })
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row mb-4">
            @if(Model.IdCine == 0)
            {
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.Direccion, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.Direccion, new { @class = "form-control hidden", @readonly = true ,@id="txtdirecion" })
                </div>
            }
            else
            {
                <div class="col-md-6">
                    @Html.LabelFor(model => Model.Direccion, new { @class = "hidden" })
                    @Html.TextBoxFor(model => Model.Direccion, new { @class = "form-control hidden", @readonly = true ,@id="txtdirecion", @onchange= "codeAddress()" })
                </div>
            }
            <div class="col-md-6">
                <div class="text-center" style="margin-top:25px">
                    <button class="btn btn-success" type="submit"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                    <a id="btnCancelar" class="btn btn-danger" href="@Url.Action("GetAll", "Cine")"><i class="fa-solid fa-right-from-bracket"></i> Volver</a>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="text-lg-start">
        <p>Selecciona la direccion del cine en el mapa</p>
    </div>
   
    <div>
        <div id="map"></div>

    </div>
    
}
@section Scripts{
    <script type="text/javascript">
        (g => { var h, a, k, p = "The Google Maps JavaScript API", c = "google", l = "importLibrary", q = "__ib__", m = document, b = window; b = b[c] || (b[c] = {}); var d = b.maps || (b.maps = {}), r = new Set, e = new URLSearchParams, u = () => h || (h = new Promise(async (f, n) => { await (a = m.createElement("script")); e.set("libraries", [...r] + ""); for (k in g) e.set(k.replace(/[A-Z]/g, t => "_" + t[0].toLowerCase()), g[k]); e.set("callback", c + ".maps." + q); a.src = `https://maps.${c}apis.com/maps/api/js?` + e; d[q] = f; a.onerror = () => h = n(Error(p + " could not load.")); a.nonce = m.querySelector("script[nonce]")?.nonce || ""; m.head.append(a) })); d[l] ? console.warn(p + " only loads once. Ignoring:", g) : d[l] = (f, ...n) => r.add(f) && u().then(() => d[l](f, ...n)) })({
            key: "AIzaSyCSKBDdPPlfca_zTwyxKiicRQn1qfgRjLw",
            v: "beta"
            // Add other bootstrap parameters as needed, using camel case.
            // Use the 'v' parameter to indicate the version to load (alpha, beta, weekly, etc.)
        });

        // Initialize and add the map
        let map;
        var marker;

        async function initMap() {
            // The location of Uluru
            const position = { lat: 19.430570307662446, lng: -99.16166352568936 };
            // Request needed libraries.

            const { Map } = await google.maps.importLibrary("maps");

            // The map, centered at Uluru
            map = new Map(document.getElementById("map"), {
                zoom: 13,
                center: position,
                mapId: "DEMO_MAP_ID",
            });

            // The marker, positioned at Uluru
            let infoWindow = new google.maps.InfoWindow({
                content: "Presiona la locacion",
                position: position,
            });
            infoWindow.open(map);




            //obtener la dirrecion
            google.maps.event.addListener(map, 'click', function (event) {
                infoWindow.close();
                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({
                    'latLng': event.latLng
                }, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (results[0]) {
                            $("#txtdirecion").val(results[0].formatted_address);
                            

                             marker = new google.maps.Marker({
                               
                                map: map,
                                position: results[0].geometry.location
                            });
                            // To add the marker to the map, call setMap();
                            
                            marker.setMap(map);
                        }
                         
                    }
                    
                });
                marker.setMap(null);
            })
            function codeAddress() {
                var address = document.getElementById('txtdirecion').value;
                geocoder.geocode({ '"txtdirecion': address }, function (results, status) {
                    if (status == 'OK') {
                        map.setCenter(results[0].geometry.location);
                        var marker = new google.maps.Marker({
                            map: map,
                            position: results[0].geometry.location
                        });
                    } else {
                        alert('Geocode was not successful for the following reason: ' + status);
                    }
                });
            }

         }

        initMap();

    </script>
}

PL/Views/Cine/GetAll.cshtml
@model ML.Cine;
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
<div class="text-lg-start">
    <h2>Cines</h2>
    <h5>Listas de Cines registrados </h5>
</div>
<hr />

<a type="button" href="@Url.Action("Form", "Cine")" class="btn btn-outline-success btn-lg w-25 p-3"><i class="bi bi-person-add"></i></a>
<hr />
<div class=" table-responsive">
    <table class="table table-hover" id="TablaDepartamento">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Id Cine</th>
                <th scope="col">Nombre del cine</th>
                <th scope="col">Direcion del cine</th>
                <th scope="col">Zona</th>
                <th scope="col">Ventas</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (ML.Cine cine in Model.Cines)
            {
                <tr>
                    <td>
                        <a type="button" class="btn btn-outline-warning btn-lg" href="@Url.Action("Form", "Cine", new {IdCine = cine.IdCine})"><i class="bi bi-pencil-square"></i></a>
                    </td>
                    <td>@cine.IdCine</td>
                    <td>@cine.Nombre</td>
                    <td>@cine.Direccion</td>
                    <td>@cine.Zona.Nombre</td>
                    <td>@cine.Ventas</td>
                    <td>
                        <a href="@Url.Action("Delete","Cine" , new { IdCine = cine.IdCine})" onclick="return confirm('Estas seguro de eliminar este registro');" type="button" class="btn btn-outline-danger btn-lg"><i class="bi bi-trash3"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

<script type="text/javascript">
    let table = new DataTable('#TablaDepartamento', {
        responsive: true,
        "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "Todos"]],
        searching: false,
        language: {
            url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
        },
    });

</script>

PL/Views/Cine/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Vale", "GetAll", "Cine", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>